version: '3'
services:
  web:
    build:
      context: . # since we are manually telling the path for docker file we have to specify from where docker should pull the files
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app